"""presupuesto: add plan table and link reglas to plan

Revision ID: 00e56665d3ad
Revises: 35304da7955f
Create Date: 2025-11-08 22:19:01.294541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e56665d3ad'
down_revision = '35304da7955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to be idempotent ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Create table presupuesto_planes only if it does not exist
    if 'presupuesto_planes' not in inspector.get_table_names():
        op.create_table('presupuesto_planes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=150), nullable=False),
        sa.Column('fecha_inicio', sa.Date(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('presupuesto_planes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_presupuesto_planes_user_id'), ['user_id'], unique=False)

    # Add column presupuesto_id to presupuestos if it's not present
    presupuestos_cols = [c['name'] for c in inspector.get_columns('presupuestos')]
    if 'presupuesto_id' not in presupuestos_cols:
        with op.batch_alter_table('presupuestos', schema=None) as batch_op:
            batch_op.add_column(sa.Column('presupuesto_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_presupuestos_presupuesto_id'), ['presupuesto_id'], unique=False)
            # provide a name for the foreign key constraint
            batch_op.create_foreign_key('fk_presupuestos_presupuesto_id_presupuesto_planes', 'presupuesto_planes', ['presupuesto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_presupuestos_presupuesto_id'))
        batch_op.drop_column('presupuesto_id')

    with op.batch_alter_table('presupuesto_planes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuesto_planes_user_id'))

    op.drop_table('presupuesto_planes')
    # ### end Alembic commands ###
