"""Add alias to cuentas

Revision ID: 1cf63fe5ea2c
Revises: 46cfce76bebf
Create Date: 2025-11-08 16:28:30.616958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf63fe5ea2c'
down_revision = '46cfce76bebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
