"""add presupuestos

Revision ID: 35304da7955f
Revises: 2b7f9e4d8c12
Create Date: 2025-11-08 22:15:33.185156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35304da7955f'
down_revision = '2b7f9e4d8c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presupuestos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presupuestos_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presupuestos_user_id'))
        batch_op.drop_index(batch_op.f('ix_presupuestos_categoria_id'))

    op.drop_table('presupuestos')
    # ### end Alembic commands ###
