"""add detalle to movimientos

Revision ID: 3dab7baa174b
Revises: 6d3f9b0b2c7a
Create Date: 2026-03-12 10:36:47.220201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dab7baa174b'
down_revision = '6d3f9b0b2c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_column('detalle')

    # ### end Alembic commands ###
