"""Crear tabla tipos_cambio

Revision ID: 9600d46315de
Revises: bbd021643d51
Create Date: 2025-07-09 09:05:19.881760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9600d46315de'
down_revision = 'bbd021643d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moneda')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipos_cambio')
    # ### end Alembic commands ###
