"""add descripcion to comercios

Revision ID: eccc4c39b9a8
Revises: 3dab7baa174b
Create Date: 2026-03-12 10:50:06.238530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccc4c39b9a8'
down_revision = '3dab7baa174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
